### PR TITLE
BINGET opcode in parser, fixes #1

### LINKED ISSUE #1: Decode error for valid Pickle
Following Pickle leads to decode error:

```
gAJ9cQEoVQdleHBpcmVzcQJOVQN1dGNxA4hVBGFyZ3NxBF1xBWNzZW9lbmdpbmUKUGFja2V0CnEGKYFxByhVF3dvcmRzdGF0X2NvdW50X3BlcmlvZGljcQhN
MgNdcQl9cQooVRNzYXZlX3Jlc3VsdF9iYWNrZW5kcQtoCFULZXhhY3Rfd29yZHNxDIhVBHNpdGVxDVUTaHR0cDovL29zdHJvdm9rLnJ1L3EOVQdrZXl3b3Jk
cQ9YIAAAANC+0YLQtdC70Lgg0LIg0Y/RgNC+0YHQu9Cw0LLQu9C1cRBVDGV4YWN0X3BocmFzZXERiHV0YmFVBWNob3JkcRJOVQljYWxsYmFja3NxE05VCGVy
cmJhY2tzcRROVQd0YXNrc2V0cRVOVQJpZHEWVSQ1ODRmMWNiMS0zYzc0LTQyNGEtOGEzYi05NjhlNzIyODk5ZjRxF1UHcmV0cmllc3EYSwBVBHRhc2txGVUg
c2VvZW5naW5lLnRhc2tzLm1ha2VfcmVzdWx0X3Rhc2txGlUDZXRhcRtOVQZrd2FyZ3NxHH1xHXUu
```

``` S="...",
pickle:pickle_to_term(base64:decode(S)).
** exception error: no function clause matching 
                    pickle:step_machine({mach,
                                            [<<"save_result_backend">>,mark,
                                             {dictionary,
                                                 {dict,0,16,16,8,80,48,
                                                     {[],[],[],[],[],[],[],[],[],[],[],[],[],...},
                                                     {{[],[],[],[],[],[],[],[],[],[],[],...}}}},
                                             {list,[]},
                                             818,<<"wordstat_count_periodic">>,mark,
                                             {pickle_object,
                                                 {pickle_global,<<"seoengine">>,<<"Packet">>},
                                                 {},undefined},
                                             {list,[]},
                                             <<"args">>,true,<<"utc">>,none,<<"expires">>,mark,
                                             {dictionary,{dict,0,16,16,8,80,48,{...},...}}],
                                            {dict,11,16,16,8,80,48,
                                                {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
                                                {{[],
                                                  [[3|<<"utc">>]],
                                                  [[6|{pickle_global,<<"seoengine">>,<<"Packet">>}]],
                                                  [[9|{list,[]}]],
                                                  [],[],
                                                  [[2|<<"expires">>]],
                                                  [[5|{list,[]}]],
                                                  [[8|<<"wordstat_cou"...>>]],
                                                  [[11|<<"save_res"...>>]],
                                                  [],
                                                  [[1|{...}]],
                                                  [[4|...]],
                                                  [[...]],
                                                  [...],...}}},
                                            false},
                                        <<104,8,85,11,101,120,97,99,116,95,119,111,114,100,115,
                                          113,12,136,85,4,115,105,116,101,113,13,85,...>>) (src/pickle.erl, line 140)
     in function  pickle:run_machine/2 (src/pickle.erl, line 129)
     in call from pickle:pickle_to_term/1 (src/pickle.erl, line 73)
```

But works good in Python

```
>>> pickle.loads(base64.decodestring(s))
{'args': [<Packet(wordstat_count_periodic, job_id=818 args=[], kwargs={'save_result_backend': 'wordstat_count_periodic', 'exact_words': True, 'site': 'http://ostrovok.ru/', 'keyword': u'\u043e\u0442\u0435\u043b\u0438 \u0432 \u044f\u0440\u043e\u0441\u043b\u0430\u0432\u043b\u0435', 'exact_phrase': True})>],
 'callbacks': None,
 'chord': None,
 'errbacks': None,
 'eta': None,
 'expires': None,
 'id': '584f1cb1-3c74-424a-8a3b-968e722899f4',
 'kwargs': {},
 'retries': 0,
 'task': 'seoengine.tasks.make_result_task',
 'taskset': None,
 'utc': True}

```

### PR DESCRIPTION
**Pull request by seriyps**
see #1

### CODE REVIEW

**Comment by jdavisp3** [comment]
Thanks very much! Could you add a unit test that covers this case?

**Comment by seriyps** [comment]
The problem about unit-tests is that I don't really know how to generate corresponding pickle binary: I just fetched that packet from production server and tested it locally until it parses successfully.
If you can help with minimized example of such packet ($h opcode), I will add unit-tests immidiately.

**Comment by seriyps** [comment]
oh, found it:

``` python
>>> o = object()
>>> pickletools.dis(pickle.dumps((o, o), protocol=2))
    0: \x80 PROTO      2
    2: c    GLOBAL     '__builtin__ object'
   22: q    BINPUT     0
   24: )    EMPTY_TUPLE
   25: \x81 NEWOBJ
   26: q    BINPUT     1
   28: h    BINGET     1
   30: \x86 TUPLE2
   31: q    BINPUT     2
   33: .    STOP
highest protocol among opcodes = 2

```

Will add unittest now

**Comment by jdavisp3** [comment]
Would something like this work?

``` erlang
     ?_assertEqual(pickle_to_term(<<16#80, 2, $K, 1, $q, 0, $K, 2, $h, 0, $.>>), 1),
```

**Comment by seriyps** [comment]
No:

```
pickle:pickle_to_term(<<16#80, 2, $K, 1, $q, 0, $K, 2, $h, 0, $.>>).
** exception error: no match of right hand side value [1,2,1]
     in function  pickle:step_machine/2 (src/pickle.erl, line 307)
     in call from pickle:run_machine/2 (src/pickle.erl, line 129)
     in call from pickle:pickle_to_term/1 (src/pickle.erl, line 73)

```

I found the minimal example:

```
o = []
pickletools.dis(pickle.dumps((o, o), protocol=2))
    0: \x80 PROTO      2
    2: ]    EMPTY_LIST
    3: q    BINPUT     0
    5: h    BINGET     0
    7: \x86 TUPLE2
    8: q    BINPUT     1
   10: .    STOP
highest protocol among opcodes = 2

```

Will add now, don't worry =)

**Comment by seriyps** [comment]
ready

**Comment by jdavisp3** [comment]
Cool. Interestingly, my example does de-pickle in python:

``` python
>>> s = [128,2,75,1,113,0,75,2,104,0,46]
>>> ''.join(map(chr, s))
'\x80\x02K\x01q\x00K\x02h\x00.'
>>> pickle.loads(''.join(map(chr, s)))
1
```

**Comment by seriyps** [comment]
Thanks.

about your example: it depickles successfully, but pickle disassembler say that there is an warning, so your pickle, is not correct in strict mode:

```
pickletools.dis('\x80\x02K\x01q\x00K\x02h\x00.')
    0: \x80 PROTO      2
    2: K    BININT1    1
    4: q    BINPUT     0
    6: K    BININT1    2
    8: h    BINGET     0
   10: .    STOP
highest protocol among opcodes = 2

ValueError: stack not empty after STOP: [int, int]
```

**Comment by jdavisp3** [comment]
Ah, ok. Well we don't need to fix that then.

**Pull request merged**
